//collections importing here
import "../../api/users/collection"
import "../../api/users/publication"
import "../../api/categories/collection"
import "../../api/categories/publication"
import "../../api/categories/methods"
import "../../api/images/collection"
import "../../api/images/publication"
import "../../api/products/methods"
import "../../api/products/publication"
import "../../api/products/collection"
import "../../api/reviews/collection"
import "../../api/reviews/methods"
import "../../api/favorites/methods"
import "../../api/favorites/collection"
import "../../api/favorites/publication"